// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_listId_ from "./routes/[listId].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $TodoListView from "./islands/TodoListView.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[listId].tsx": $_listId_,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/TodoListView.tsx": $TodoListView,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
